### ISSUE TITLE
Rcplex fails to compile

### ISSUE THREAD

**Issue by tdhock** [tdhock/data.table-revdeps#15]
below we see that Rcplex installs using gcc 8.5.0
```
th798@cn52:/tmp/th798/7382815/RtmpXQBHTs/downloaded_packages$ R CMD INSTALL Rcplex_0.3-6.tar.gz --configure-args="--with-cplex-dir=/home/th798/cplex"
* installing to library ‘/projects/genomic-ml/lib64/R/library’
* installing *source* package ‘Rcplex’ ...
** package ‘Rcplex’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gawk... gawk
'config' variable 'CPP' is defunct
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ilcplex/cplex.h usability... yes
checking ilcplex/cplex.h presence... yes
checking for ilcplex/cplex.h... yes
checking for library containing CPXversion... none required
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C compiler: ‘gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)’
gcc -I"/home/th798/lib64/R/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -g -O2  -c Rcplex.c -o Rcplex.o
gcc -I"/home/th798/lib64/R/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -g -O2  -c Rcplex_QCP.c -o Rcplex_QCP.o
gcc -I"/home/th798/lib64/R/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -g -O2  -c Rcplex_params.c -o Rcplex_params.o
gcc -I"/home/th798/lib64/R/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -g -O2  -c Rcplex_utils.c -o Rcplex_utils.o
gcc -I"/home/th798/lib64/R/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -g -O2  -c init.c -o init.o
gcc -shared -L/home/th798/.conda/envs/emacs1/lib -Wl,-rpath=/home/th798/.conda/envs/emacs1/lib -L/home/th798/lib -Wl,-rpath=/home/th798/lib -L/home/th798/lib64 -Wl,-rpath=/home/th798/lib64 -o Rcplex.so Rcplex.o Rcplex_QCP.o Rcplex_params.o Rcplex_utils.o init.o -L/home/th798/cplex/lib/x86-64_linux/static_pic -lcplex -lm -lpthread -ldl
installing to /projects/genomic-ml/lib64/R/library/00LOCK-Rcplex/00new/Rcplex/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Rcplex)
```
Below we see that Rcplex does not compile using gcc 12.2.0
```
th798@cn52:/tmp/th798/7382815/RtmpXQBHTs/downloaded_packages$ ~/R/R-devel/bin/R CMD INSTALL Rcplex_0.3-6.tar.gz --configure-args="--with-cplex-dir=/home/th798/cplex"
* installing to library ‘/projects/genomic-ml/R/R-devel/library’
* installing *source* package ‘Rcplex’ ...
** package ‘Rcplex’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gawk... gawk
'config' variable 'CPP' is defunct
checking for gcc... /packages/gcc/12.2.0-nnbserq/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /packages/gcc/12.2.0-nnbserq/bin/gcc accepts -g... yes
checking for /packages/gcc/12.2.0-nnbserq/bin/gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /packages/gcc/12.2.0-nnbserq/bin/gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ilcplex/cplex.h usability... yes
checking ilcplex/cplex.h presence... yes
checking for ilcplex/cplex.h... yes
checking for library containing CPXversion... none required
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C compiler: ‘gcc (Spack GCC) 12.2.0’
/packages/gcc/12.2.0-nnbserq/bin/gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c Rcplex.c -o Rcplex.o
/packages/gcc/12.2.0-nnbserq/bin/gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c Rcplex_QCP.c -o Rcplex_QCP.o
/packages/gcc/12.2.0-nnbserq/bin/gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c Rcplex_params.c -o Rcplex_params.o
/packages/gcc/12.2.0-nnbserq/bin/gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c Rcplex_utils.c -o Rcplex_utils.o
/packages/gcc/12.2.0-nnbserq/bin/gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c init.c -o init.o
/packages/gcc/12.2.0-nnbserq/bin/gcc -shared -L/home/th798/.conda/envs/emacs1/lib -Wl,-rpath=/home/th798/.conda/envs/emacs1/lib -L/home/th798/lib -Wl,-rpath=/home/th798/lib -L/home/th798/lib64 -Wl,-rpath=/home/th798/lib64 -o Rcplex.so Rcplex.o Rcplex_QCP.o Rcplex_params.o Rcplex_utils.o init.o -L/home/th798/cplex/lib/x86-64_linux/static_pic -lcplex -lm -lpthread -ldl
Rcplex_QCP.o:(.bss+0x0): multiple definition of `env'
Rcplex.o:(.bss+0x0): first defined here
Rcplex_QCP.o:(.bss+0x8): multiple definition of `lp'
Rcplex.o:(.bss+0x8): first defined here
Rcplex_QCP.o:(.bss+0x10): multiple definition of `numcalls'
Rcplex.o:(.bss+0x10): first defined here
Rcplex_QCP.o:(.bss+0x14): multiple definition of `max_numcalls'
Rcplex.o:(.bss+0x14): first defined here
Rcplex_QCP.o:(.bss+0x18): multiple definition of `forceCplxClose'
Rcplex.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
make: *** [/home/th798/R/R-devel/share/make/shlib.mk:10: Rcplex.so] Error 1
ERROR: compilation failed for package ‘Rcplex’
* removing ‘/projects/genomic-ml/R/R-devel/library/Rcplex’
```
The problem seems to be the difference between these two lines below:
```
gcc 
 -I"/home/th798/lib64/R/include" 
 -DNDEBUG -I/home/th798/cplex/include  
 -I/home/th798/.conda/envs/emacs1/include 
 -I/home/th798/include   
 -m64 
 -fPIC 
 -fpic  
 -g 
 -O2  
 -c Rcplex_QCP.c 
 -o Rcplex_QCP.o
/packages/gcc/12.2.0-nnbserq/bin/gcc 
 -I"/home/th798/R/R-devel/include" 
 -DNDEBUG -I/home/th798/cplex/include  
 -I/home/th798/.conda/envs/emacs1/include 
 -I/home/th798/include   
 -m64 
 -fPIC 
 -fpic  
 -I/packages/gcc/12.2.0-nnbserq/include 
 -I/packages/zstd/1.5.2-cs5ansz/include 
 -I/packages/zlib/1.2.13-po6bkge/include 
 -I/packages/mpc/1.2.1-nnfoiwh/include 
 -I/packages/mpfr/4.1.0-yfsqqka/include 
 -I/packages/gmp/6.2.1-7ydtie6/include  
 -c Rcplex_QCP.c 
 -o Rcplex_QCP.o
```
The important difference between the two commands above is the gcc version, which is shown by the output below (recompile Rcplex_QCP.c then relink). First command recompiles with new gcc-12.2.0, then linking fails. Second command recompiles with old gcc-8.5.0, then linking is ok. This says there is some problem (new error checking? with the new gcc.
```
th798@cn52:/tmp/th798/7382815/RtmpXQBHTs/downloaded_packages/Rcplex/src$ /packages/gcc/12.2.0-nnbserq/bin/gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c Rcplex_QCP.c -o Rcplex_QCP.o && /packages/gcc/12.2.0-nnbserq/bin/gcc -shared -L/home/th798/.conda/envs/emacs1/lib -Wl,-rpath=/home/th798/.conda/envs/emacs1/lib -L/home/th798/lib -Wl,-rpath=/home/th798/lib -L/home/th798/lib64 -Wl,-rpath=/home/th798/lib64 -o Rcplex.so Rcplex.o Rcplex_QCP.o Rcplex_params.o Rcplex_utils.o init.o -L/home/th798/cplex/lib/x86-64_linux/static_pic -lcplex -lm -lpthread -ldl
Rcplex_QCP.o:(.bss+0x0): multiple definition of `env'
Rcplex.o:(.bss+0x0): first defined here
Rcplex_QCP.o:(.bss+0x8): multiple definition of `lp'
Rcplex.o:(.bss+0x8): first defined here
Rcplex_QCP.o:(.bss+0x10): multiple definition of `numcalls'
Rcplex.o:(.bss+0x10): first defined here
Rcplex_QCP.o:(.bss+0x14): multiple definition of `max_numcalls'
Rcplex.o:(.bss+0x14): first defined here
Rcplex_QCP.o:(.bss+0x18): multiple definition of `forceCplxClose'
Rcplex.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
th798@cn52:/tmp/th798/7382815/RtmpXQBHTs/downloaded_packages/Rcplex/src$ gcc -I"/home/th798/R/R-devel/include" -DNDEBUG -I/home/th798/cplex/include  -I/home/th798/.conda/envs/emacs1/include -I/home/th798/include   -m64 -fPIC -fpic  -I/packages/gcc/12.2.0-nnbserq/include -I/packages/zstd/1.5.2-cs5ansz/include -I/packages/zlib/1.2.13-po6bkge/include -I/packages/mpc/1.2.1-nnfoiwh/include -I/packages/mpfr/4.1.0-yfsqqka/include -I/packages/gmp/6.2.1-7ydtie6/include  -c Rcplex_QCP.c -o Rcplex_QCP.o && /packages/gcc/12.2.0-nnbserq/bin/gcc -shared -L/home/th798/.conda/envs/emacs1/lib -Wl,-rpath=/home/th798/.conda/envs/emacs1/lib -L/home/th798/lib -Wl,-rpath=/home/th798/lib -L/home/th798/lib64 -Wl,-rpath=/home/th798/lib64 -o Rcplex.so Rcplex.o Rcplex_QCP.o Rcplex_params.o Rcplex_utils.o init.o -L/home/th798/cplex/lib/x86-64_linux/static_pic -lcplex -lm -lpthread -ldl
th798@cn52:/tmp/th798/7382815/RtmpXQBHTs/downloaded_packages/Rcplex/src$ 
```

**Comment by ben-schwen** [comment]
It basically says that it doesn't like that the global vars: `env`, `lp`, `numcalls`, `max_numcalls` and `forceCplxClose` are defined multiple times, since they are defined in `src/Rcplex_QCP.c` and `src/Rcplex.c`

edit: Apparently there is already a proposed fix at the github mirror https://github.com/cran/Rcplex/issues/1 which Stefan (@theussl) might add

**Comment by tdhock** [comment]
yes I emailed Stefan about that, so I guess that is a bug on his side, nothing for us to fix.
